language: node_js
node_js: node
deploy: guarded-refuge-39384
  provider: heroku
  api_key:
    secure: OgaS6nB3odJEkRd1ViIBgn7oegapMLBdCp6pVQc12wpetMNdENoyGRoKCkidlTCJZKqrvp5VkbIFtOvcngBeESgN0PBh9YpC47XPIgxiGwz09u3xQxiafAP4Lf7wHV3bP085SLuQ0v/uXD6KSzwa9gqscxsvjyihE6CqJzwwg1lhXpRJvRJQFoHlLBtUTUEkNlc6B9vP40YnDMRhIT1gUBh+WPlvT9asNZylI9L0A6yQmOUd6GE9ccxP0iMZY1oqzSkadrLiuvLgPkSyGmhe/2CLkYa3cRqPuxV4UYFOcJ7wnKjizTjWNt+xXjkvU2c3K+qav/P2Ra003YYG2mgJjNlkaayOpAOI9bW2Xw6PiC7me1HnYQ22sgmNRbLhrPGtudEstF6p+d/nCFlMsJhx5itv72yjv9HhLA2N81QLEXYPaCBMyFT+/4+46pr10LKgTTsZbyZjjtLXgja0ivi90Moen8Hs5PxIEfKRsWnkvXy3vTrUqtZvP/6vCdxbW92J0vdBq2n2kdZ2dkuuc6Hu4qW5Wowi9Dm5+JNm6SFGu13mkj30qmAjK4Rone0P8GowZwf21cdPqUEzywvRRl5TkuTtPDuZnmZBrlQqHaEV15BGI9tBX+hItHbdmAt48mUkfY+PCOytLAY2H0dpX4ovIIeo4yFqpconp8/LWTDFXZU=
  app: epic-throwaway
  on:
    repo: ElenaG518/epic-throwaway